spring:
  datasource:
    url: jdbc:mysql://localhost:3308/fastpick?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6380

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: fastpick-ticketing
      auto-offset-reset: earliest
    producer:
      acks: all

  output:
    ansi:
      enabled: ALWAYS

fastpick:
  queue:
    enter-window-size: 50
    max-active-permits-per-schedule: 20
    permit-ttl-seconds: 30
  kafka:
    topics:
      ticket-requested: ticket-requested

jwt:
  secret: aG9yYW5naS10aWdlcnMtZmFzdC1waWNrLXNlY3JldC1rZXktZm9yLWp3dA== # (아무도 모르는 우리만의 비밀 키, Base64로 인코딩된 아무 문자열이나 길게 쓰면 됩니다)